[package]
name = "kvs"
version = "0.1.0"
authors = ["Muhammad Falak <falakreyaz@gmail.com>"]
description = "Key Value Store"
edition = "2018"

[dependencies]
clap = "2.32.0"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
